### ISSUE TITLE
netscaler_nitro_request module not in documentation

### ISSUE THREAD

**Issue by giorgos-nikolopoulos** [ajitchelat/ansible#3]
Hi Ajit,

In the last PR I added the netscaler_nitro_request module documentation.

It's in modules/netscaler_nitro_request.md.

On the rendered site I get a 404 error when I try to access it.

Can you see what is wrong?

**Comment by ajitchelat** [comment]
Hi @giorgos-nikolopoulos,

The issue was that the new file you added wasn't included in the YAML configuration file for the site. I've added it now and rebuilt the site. The page should be accessible now.
